[env]
RUST_BACKTRACE = "full"

[alias]
coverage-report = "tarpaulin --engine llvm --skip-clean --all-features --out Html --output-dir ./tmp/coverage/all"
coverage-fast-inverse = "tarpaulin --engine llvm --skip-clean --features fast-inverse --out Html --output-dir ./tmp/coverage/fast_inverse"
coverage-arithmetic = "tarpaulin --engine llvm --skip-clean --no-default-features --out Html --output-dir ./tmp/coverage/arithmetic"
clippy-log = "clippy --all-targets"
benchmark-save = "bench --bench shamir_zero_benchmark -- --save-baseline main"
benchmark-compare = "bench --bench shamir_zero_benchmark -- --baseline main"
fuzz-shamir = "fuzz run shamir_roundtrip"
fuzz_5_mins = "fuzz run shamir_roundtrip -- -max_total_time=300"