[env]
RUST_BACKTRACE="full"

[alias]
coverage-report = "tarpaulin --follow-exec --timeout 60 --branch --out Html --output-dir ./tmp/coverage"
clippy-log = "clippy --all-targets &> ./tmp/clippy.log"
fuzz_shamir = "fuzz run shamir_roundtrip"
fuzz_5_mins = "fuzz run shamir_roundtrip -- -max_total_time=300"